"""add notebook color notebook relation and document file size

Revision ID: 0c9f99f8bd49
Revises: c03804bfdee5
Create Date: 2026-07-30 07:13:11.507440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0c9f99f8bd49'
down_revision: Union[str, Sequence[str], None] = 'c03804bfdee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_size', mysql.BIGINT(unsigned=True), nullable=False))
    op.add_column('notebooks', sa.Column('color', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notebooks', 'color')
    op.drop_column('documents', 'file_size')
    # ### end Alembic commands ###
