"""rename quiz status to generation_status

Revision ID: 0fae3783ff32
Revises: cbcf01455a51
Create Date: 2026-07-12 07:45:18.852738

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "0fae3783ff32"
down_revision: Union[str, Sequence[str], None] = "cbcf01455a51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quizzes",
        sa.Column(
            "target_total_points", sa.Integer(), server_default="100", nullable=False
        ),
    )
    op.add_column(
        "quizzes",
        sa.Column(
            "generation_mode",
            sa.String(length=20),
            server_default="simple",
            nullable=False,
        ),
    )
    op.add_column(
        "quizzes", sa.Column("difficulty", sa.String(length=20), nullable=True)
    )
    op.add_column("quizzes", sa.Column("custom_instruction", sa.Text(), nullable=True))
    op.add_column("quizzes", sa.Column("error_message", sa.Text(), nullable=True))
    op.add_column(
        "quizzes",
        sa.Column(
            "generation_status",
            sa.String(length=20),
            server_default="processing",
            nullable=False,
        ),
    )
    op.drop_column("quizzes", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quizzes",
        sa.Column(
            "status",
            mysql.VARCHAR(length=20),
            server_default=sa.text("'processing'"),
            nullable=False,
        ),
    )
    op.drop_column("quizzes", "generation_status")
    op.drop_column("quizzes", "error_message")
    op.drop_column("quizzes", "custom_instruction")
    op.drop_column("quizzes", "difficulty")
    op.drop_column("quizzes", "generation_mode")
    op.drop_column("quizzes", "target_total_points")
    # ### end Alembic commands ###
