"""add flashcards

Revision ID: 7bd1d471fe57
Revises: 7a53c5b16d82
Create Date: 2026-08-23 11:22:29.895210

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7bd1d471fe57"
down_revision: Union[str, Sequence[str], None] = "7a53c5b16d82"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flashcard_decks",
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("notebook_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "generation_status", sa.String(length=20), server_default="manual", nullable=False
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("source_document_ids", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["notebook_id"], ["notebooks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_flashcard_decks_id"), "flashcard_decks", ["id"], unique=False)
    op.create_index(
        "ix_flashcard_decks_user_notebook",
        "flashcard_decks",
        ["user_id", "notebook_id"],
        unique=False,
    )
    op.create_table(
        "flashcard_study_sessions",
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("deck_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("new_cards_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("review_cards_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("reviewed_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["deck_id"], ["flashcard_decks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_flashcard_sessions_user_deck_status",
        "flashcard_study_sessions",
        ["user_id", "deck_id", "status"],
        unique=False,
    )
    op.create_table(
        "flashcards",
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("deck_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("front", sa.Text(), nullable=False),
        sa.Column("back", sa.Text(), nullable=False),
        sa.Column("hint", sa.Text(), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("source_document_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("source_chunk_id", sa.String(length=255), nullable=True),
        sa.Column("source_metadata", sa.JSON(), nullable=True),
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_suspended", sa.Boolean(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["deck_id"], ["flashcard_decks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_flashcards_deck_position", "flashcards", ["deck_id", "position"], unique=False
    )
    op.create_index(
        "ix_flashcards_deck_suspended", "flashcards", ["deck_id", "is_suspended"], unique=False
    )
    op.create_index(op.f("ix_flashcards_id"), "flashcards", ["id"], unique=False)
    op.create_table(
        "flashcard_review_logs",
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("card_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("session_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("rating", sa.String(length=10), nullable=False),
        sa.Column("state_before", sa.String(length=20), nullable=False),
        sa.Column("state_after", sa.String(length=20), nullable=False),
        sa.Column("due_before", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stability_before", sa.Float(), nullable=True),
        sa.Column("stability_after", sa.Float(), nullable=True),
        sa.Column("difficulty_before", sa.Float(), nullable=True),
        sa.Column("difficulty_after", sa.Float(), nullable=True),
        sa.Column("scheduled_days", sa.Integer(), server_default="0", nullable=False),
        sa.Column("elapsed_days", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "reviewed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("response_time_ms", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["card_id"], ["flashcards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["session_id"], ["flashcard_study_sessions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_flashcard_review_logs_card_user_reviewed",
        "flashcard_review_logs",
        ["card_id", "user_id", "reviewed_at"],
        unique=False,
    )
    op.create_index(
        "ix_flashcard_review_logs_user_reviewed",
        "flashcard_review_logs",
        ["user_id", "reviewed_at"],
        unique=False,
    )
    op.create_table(
        "flashcard_review_states",
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("card_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("state", sa.String(length=20), server_default="new", nullable=False),
        sa.Column("due", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stability", sa.Float(), nullable=True),
        sa.Column("difficulty", sa.Float(), nullable=True),
        sa.Column("elapsed_days", sa.Integer(), server_default="0", nullable=False),
        sa.Column("scheduled_days", sa.Integer(), server_default="0", nullable=False),
        sa.Column("reps", sa.Integer(), server_default="0", nullable=False),
        sa.Column("lapses", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_review", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["card_id"], ["flashcards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("card_id", "user_id", name="uq_flashcard_review_state_card_user"),
    )
    op.create_index(
        "ix_flashcard_review_states_user_due",
        "flashcard_review_states",
        ["user_id", "due"],
        unique=False,
    )
    op.create_index(
        "ix_flashcard_review_states_user_state",
        "flashcard_review_states",
        ["user_id", "state"],
        unique=False,
    )
    op.create_table(
        "flashcard_session_cards",
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("session_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("card_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("queue_type", sa.String(length=20), nullable=False),
        sa.Column("queue_position", sa.Integer(), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("review_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("completed", sa.Boolean(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["card_id"], ["flashcards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["session_id"], ["flashcard_study_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "card_id", name="uq_flashcard_session_card"),
    )
    op.create_index(
        "ix_flashcard_session_queue",
        "flashcard_session_cards",
        ["session_id", "completed", "available_at", "queue_position"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_flashcard_session_queue", table_name="flashcard_session_cards")
    op.drop_table("flashcard_session_cards")
    op.drop_index("ix_flashcard_review_states_user_state", table_name="flashcard_review_states")
    op.drop_index("ix_flashcard_review_states_user_due", table_name="flashcard_review_states")
    op.drop_table("flashcard_review_states")
    op.drop_index("ix_flashcard_review_logs_user_reviewed", table_name="flashcard_review_logs")
    op.drop_index("ix_flashcard_review_logs_card_user_reviewed", table_name="flashcard_review_logs")
    op.drop_table("flashcard_review_logs")
    op.drop_index(op.f("ix_flashcards_id"), table_name="flashcards")
    op.drop_index("ix_flashcards_deck_suspended", table_name="flashcards")
    op.drop_index("ix_flashcards_deck_position", table_name="flashcards")
    op.drop_table("flashcards")
    op.drop_index("ix_flashcard_sessions_user_deck_status", table_name="flashcard_study_sessions")
    op.drop_table("flashcard_study_sessions")
    op.drop_index("ix_flashcard_decks_user_notebook", table_name="flashcard_decks")
    op.drop_index(op.f("ix_flashcard_decks_id"), table_name="flashcard_decks")
    op.drop_table("flashcard_decks")
    # ### end Alembic commands ###
