"""update_quiz_mode_and_json_answers

Revision ID: 940db043301d
Revises: 959282633ca2
Create Date: 2026-07-03 07:06:39.705648

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "940db043301d"
down_revision: Union[str, Sequence[str], None] = "959282633ca2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quiz_questions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("quiz_id", sa.BigInteger(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("question_type", sa.String(length=50), nullable=False),
        sa.Column("options", sa.JSON(), nullable=True),
        sa.Column("correct_answer", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["quiz_id"], ["quizzes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quiz_questions_id"), "quiz_questions", ["id"], unique=False
    )
    op.create_table(
        "quiz_results",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("quiz_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("answers_json", sa.JSON(), nullable=False),
        sa.Column("ai_comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["quiz_id"], ["quizzes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quiz_results_id"), "quiz_results", ["id"], unique=False)
    op.add_column("quizzes", sa.Column("user_id", sa.BigInteger(), nullable=False))
    op.alter_column(
        "quizzes", "quiz_type", existing_type=mysql.VARCHAR(length=50), nullable=False
    )
    op.alter_column(
        "quizzes",
        "created_at",
        existing_type=mysql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("(now())"),
    )
    op.create_foreign_key(
        None, "quizzes", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "quizzes", type_="foreignkey")
    op.alter_column(
        "quizzes",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=mysql.TIMESTAMP(),
        existing_nullable=True,
        existing_server_default=sa.text("(now())"),
    )
    op.alter_column(
        "quizzes", "quiz_type", existing_type=mysql.VARCHAR(length=50), nullable=True
    )
    op.drop_column("quizzes", "user_id")
    op.drop_index(op.f("ix_quiz_results_id"), table_name="quiz_results")
    op.drop_table("quiz_results")
    op.drop_index(op.f("ix_quiz_questions_id"), table_name="quiz_questions")
    op.drop_table("quiz_questions")
    # ### end Alembic commands ###
