"""add flashcard review state step

Revision ID: b78fd66b4c37
Revises: 7bd1d471fe57
Create Date: 2026-08-23 11:35:52.516190

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b78fd66b4c37"
down_revision: Union[str, Sequence[str], None] = "7bd1d471fe57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("flashcard_review_states", sa.Column("step", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("flashcard_review_states", "step")
    # ### end Alembic commands ###
