"""add_mongo_id_to_documents

Revision ID: cbcf01455a51
Revises: 9cd3879cfd0c
Create Date: 2026-07-08 03:29:15.111323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cbcf01455a51'
down_revision: Union[str, Sequence[str], None] = '9cd3879cfd0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('mongo_id', sa.String(length=50), nullable=True))
    op.drop_column('documents', 'parsed_content')
    op.drop_column('documents', 'summary_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('summary_content', mysql.TEXT(), nullable=True))
    op.add_column('documents', sa.Column('parsed_content', mysql.TEXT(), nullable=True))
    op.drop_column('documents', 'mongo_id')
    # ### end Alembic commands ###
